name: Deploy docker image to EC2

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/outline
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/outline
          docker run --env-file .env -p 3000:3000 --network=host ${{ secrets.DOCKER_HUB_USERNAME }}/outline

# - name: Set up Docker
#   uses: actions/setup-docker@v2
#   with:
#     dockerfile: Dockerfile

# - name: Build the Docker image
#   run: docker build -t huitingwu/outline

# - name: Log in to Docker Hub
#   run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

# - name: Push the docker image
#   run: docker push huitingwu/outline

# - name: deploy
#   run: |
#     docker pull huitingwu/outline
#     docker run --env-file .env -p 3000:3000 --network=host huitingwu/outline
