name: Deploy docker image to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/outline

      - name: Deploy to Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Hello from github action, start deploy main to ec2!"
            docker stop outline || true
            docker rm outline || true
            cd /home/ubuntu/outline-github
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/outline
            docker rm -f outline || true
            docker run -d --name outline --restart=always --env-file .env -p 3000:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/outline
            docker image prune -a -f --filter "label!=latest"
