name: Deploy docker image to EC2

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: actions/setup-docker@v2
        with:
          dockerfile: Dockerfile

      - name: Build the Docker image
        run: docker build -t huitingwu/outline

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push the docker image
        run: docker push huitingwu/outline

      - name: deploy
        run: |
          docker pull huitingwu/outline
          docker run --env-file .env -p 3000:3000 --network=host huitingwu/outline
