name: Deploy to EC2 on merge

'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Hello from github action, start deploy main to ec2!"
            cd /home/ubuntu/outline-github
            git switch main
            git pull origin main --force
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            npm --help
            npm install
            npx pm2 restart outline
