name: Deploy to EC2 on merge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install pm2
        run: npm install -g pm2
      - name: deploy to ec2
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.HOST_DNS }}'
          username: '${{ secrets.EC2_USERNAME }}'
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Hello from github action, start deploy main to ec2"
            cd /home/ubuntu/outline-github
            git checkout main
            git pull
            npm install
            pm2 restart outline
